## Домашняя работа №1 по ML 

### Предсказать параметр MEDV из датасета housing.csv:
1 - модель линейной регрессии.

2 - разбить train/test на 0.8/0.2

In [1]:
import numpy as np
import pandas as pd
from numpy.linalg import inv
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.metrics import accuracy_score, roc_curve, roc_auc_score, f1_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelBinarizer

In [2]:
# Загружаем датасет
df = pd.read_csv('housing.csv', sep=',')
df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    float64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(14)
memory usage: 55.5 KB

In [4]:
df.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [5]:
# Задаем значения
X = df.iloc[:, :-1].copy()
y = df.iloc[:, -1].copy()

In [6]:
# Разбиваем датасет на валидационные и тренировочные данные
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=10)

# Обучаем модель линейной регрессии
model = LinearRegression().fit(X_train, y_train)

# Предсказываем
y_pred = model.predict(X_valid)

In [7]:
from sklearn.metrics import r2_score, mean_squared_error

# Проверяем качество метрики
print(r2_score(y_valid, y_pred))

0.6709339839115652

In [8]:
from sklearn.linear_model import Ridge, Lasso

# Проверим качество моделей Ridge, Lasso
model_Ridge = Ridge(alpha=0.8).fit(X_train, y_train)

# Предсказываем
y_pred_Ridge = model_Ridge.predict(X_valid)
y_pred_train_Ridge = model.predict(X_train)

print("Качество на валидации: %.3f" % mean_squared_error(y_valid, y_pred_Ridge))
print("Качество на обучении: %.3f" % mean_squared_error(y_train, y_pred_train_Ridge))

Качество на валидации: 34.885
Качество на обучении: 19.231

In [9]:
model_Lasso = Lasso(alpha=0.8).fit(X_train, y_train)
y_pred_train_Ridge = model.predict(X_train)
y_pred_Lasso = model_Ridge.predict(X_valid)
y_pred_train_Lasso = model.predict(X_train)

print("Качество на валидации: %.3f" % mean_squared_error(y_valid, y_pred_Lasso))
print("Качество на обучении: %.3f" % mean_squared_error(y_train, y_pred_train_Lasso))

Качество на валидации: 34.885
Качество на обучении: 19.231

Качество моделей Ridge, Lasso значительно хуже